### ISSUE TITLE
Client sometimes doesn't receive all populator blocks

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#170] opened 2017-02-16 19:24 UTC
![2017-02-16_20 19 48](https://cloud.githubusercontent.com/assets/19509275/23037187/bba57ddc-f485-11e6-8511-462ddb9f0994.png)

As you can see some of the trees look cut in half and do miss some of their blocks but they are invisible
And whenever you walk into them you start rubberbanding back to your previous position before touching the block.

For so far I've only seen this happen with oak trees in Custom Cubic.

**Comment by Niko-sk2x** [comment] 2017-02-17 04:06
This is something wrong with population code. These blocks aren't sent to client at all. Known but but I didn't make github issue for it.

**Comment by Niko-sk2x** [comment] 2017-04-30 20:50
Actually, I didn't realize this is a duplicate of #156. This report has much more information, so I'm leaving this one and closing the old one as duplicate.

**Closed as completed** 2017-05-29 13:43 UTC
Labels: Bug
