### ISSUE TITLE
Suggestion: Config option to display what mod is currently being worked on when initial world generation is happening.

### ISSUE THREAD

**Issue by border999** [Barteks2x/CubicChunks#359] opened 2018-03-03 21:30 UTC

**Comment by FyreByrns** [comment] 2018-03-03 21:35
We have *told* you that this is out of scope!

**Comment by DaMatrix** [comment] 2018-03-03 21:36
And the text would be flashing by so quickly it'd be absolutely pointless anyway

**Comment by Niko-sk2x** [comment] 2018-03-03 21:38
It wouldn't be flashing if it gets stuck, unless it's multiple mods interacting. And the issue is only when you are trying to make a modpack, so you either should know what you are doing and either figure out which mod cuses an issue by removing different mods, or use something like VisualVM or leave it to modpack developers (who would do one of the above anyway).

**Comment by Niko-sk2x** [comment] 2018-09-12 18:37
Because of reasons explained above, this is not going to happen.

**Closed as completed by Niko-sk2x** 2018-09-12 18:37 UTC
Labels: Wontfix, Feature
