### ISSUE TITLE
Cube in column not the same as stored cube!

### ISSUE THREAD

**Issue by RelativeProgramming** [Barteks2x/CubicChunks#251] opened 2017-07-15 17:57 UTC
While flying around in a custom Cubic World, the game crashes sometimes with this exception:

[latest.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1150507/latest.txt)

**Comment by Niko-sk2x** [comment] 2017-07-15 17:58
Duplicate of #250

**Comment by Niko-sk2x** [comment] 2017-07-15 17:59
Working on it right now, it's tricky to figure out what actually causes it so it may take a while.

**Closed as completed by Niko-sk2x** 2017-07-15 17:58 UTC
Labels: Bug, Duplicate
