### ISSUE TITLE
Crash with Sledgehammer mod

### ISSUE THREAD

**Issue by Xorbah** [Barteks2x/CubicChunks#438] opened 2019-04-16 10:47 UTC
*Edited by Barteks2x to use code blocks*

I decided to tweak my JVM startup arguments for better performance whilst in game and get an immediate crash when clicking play on the launcher while using CC. No crash report is created, it simply says this in the output log - 

```
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at io.github.lxgaming.sledgehammer.launch.SledgehammerLaunch.configureEnvironment(SledgehammerLaunch.java:59)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at io.github.lxgaming.sledgehammer.launch.SledgehammerTweaker.injectIntoClassLoader(SledgehammerTweaker.java:33)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
05:46:06 game info [05:46:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
05:46:06 monitor Process Monitor fatal
Process crashed with exit code 1
```

The arguments I was using goes as follows - 

```
-XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by Niko-sk2x** [comment] 2019-04-16 11:54
This appears to be an issue caused by whatever `Sledgehammer` is. It also appears to be using it's own tweaker to initialize mixin, which is not really supported by mixin. It has nothing to do with JVM arguments.

It may be using a newer version of Mixin than cubic chunks, but not specifying it in mixin config, in which case renaming Shedgehammer to something like `a_Sledgehammer.jar` should fix the issue.

Looking at it's description, It's also very likely sledgehammer will have some mixin conflicts and will not run with cubic chunks anyway. If it fails and there is a way to disable some of it's option, can try doing that.

**Comment by Xorbah** [comment] 2019-04-16 12:03
Will test and return with results. Thank you.

**Comment by Niko-sk2x** [comment] 2019-04-16 12:03
I tried it myself. The full error message is:
```
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.sledgehammer.preinit.json requires mixin subsystem version 0.7.10
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.github.lxgaming.sledgehammer.launch.SledgehammerLaunch.configureEnvironment(SledgehammerLaunch.java:59)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.github.lxgaming.sledgehammer.launch.SledgehammerTweaker.injectIntoClassLoader(SledgehammerTweaker.java:33)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:59:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
```
Which confirms my suspicion that Sledgehammer requires a newer mixin version. Renaming it's jar to be earlier than cubic chunks in alphabetical order will fix it. This is already fixed in code, and will be fixed in next release.

**Closed as completed by Niko-sk2x** 2019-04-16 12:03 UTC
Labels: Compatibility
