### ISSUE TITLE
Pitch black view underwater

### ISSUE THREAD

**Issue by Quizer9O8** [Barteks2x/CubicChunks#203] opened 2017-05-28 13:44 UTC
This might be a lighting and fog bug, you can barely see underwater below Y:0
![image](https://cloud.githubusercontent.com/assets/19509275/26529215/5f833f40-43bc-11e7-90c7-a183bafeff8a.png)
![image](https://cloud.githubusercontent.com/assets/19509275/26529228/7c4cb7be-43bc-11e7-9d21-10508f1d997f.png)

**Comment by Niko-sk2x** [comment] 2017-05-28 14:47
It seems like lighting isn't properly updated in this case. I think I know the exact cause  of this. Is it better after re-entering the world? If so, it's actually a duplicate of #6

**Comment by Niko-sk2x** [comment] 2017-05-28 23:33
This actually is another lighting bug, because it also is incorrect serverside. One thing I should do is make the client fix it's own lighting bugs as player gets closer. This is what partial issue looks like:
![2017-05-29_01 30 38](https://cloud.githubusercontent.com/assets/1349112/26532927/ca5bb1c4-440e-11e7-82da-7dacb4c2fb55.png)

**Comment by Niko-sk2x** [comment] 2017-11-25 07:58
This is actually a lighting bug, and light propagation is being rewritten (most of the issues can't really be fixed in the current code). I will make a separate issue for lighting.

**Closed as completed by Niko-sk2x** 2017-11-25 07:58 UTC
Labels: Bug
