### ISSUE TITLE
Crash when clicking "Customize" on Custom Cubic world setting

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Barteks2x/CubicChunks#380] opened 2018-07-12 17:05 UTC
[LOG](https://pastebin.com/rHfsn2b6) (should include all versions for Forge, the mod, malisisCore, etc)

there is nothing much to say, i just clicked it and it crashed

**Comment by Kabaril** [comment] 2018-07-18 15:44
Using Forge 2705 works for me

**Comment by Niko-sk2x** [comment] 2018-09-12 18:35
Already fixed. Duplicate of #341.

**Closed as completed by Niko-sk2x** 2018-09-12 18:35 UTC
Labels: Bug, Duplicate
