### ISSUE TITLE
Fix server performance with CC when loading several chunks

### ISSUE THREAD

**Issue by muzikbike** [Barteks2x/CubicChunks#551] opened 2020-07-23 17:50 UTC
The server clearly isn't very happy with CC's existence (1.16.1, build 302), spending about 90% of its time completely frozen. 1.12.2 doesn't complain nearly as much, so this should probably be looked at.

![2020-07-23_18 42 11](https://user-images.githubusercontent.com/52297970/88320320-54447000-cd15-11ea-9569-37492afc812a.png)
![2020-07-23_18 49 09](https://user-images.githubusercontent.com/52297970/88320324-560e3380-cd15-11ea-9f84-997eaf311500.png)
![2020-07-23_18 35 54](https://user-images.githubusercontent.com/52297970/88320339-5ad2e780-cd15-11ea-93af-59065eec6e8f.png)
![2020-07-23_18 35 58](https://user-images.githubusercontent.com/52297970/88320340-5c9cab00-cd15-11ea-93bb-efb7dc1a1562.png)

**Comment by Cyclonit** [comment] 2020-07-23 19:23
Performance is clearly something to be looked at, but I can't reproduce your results at all. Did you do anything worth mentioning while taking the screenshots?

**Comment by muzikbike** [comment] 2020-07-23 19:34
Moving?

**Comment by Cyclonit** [comment] 2020-07-23 20:10
Can you provide the specs of your PC please? I can't reproduce that level of load on my machine and having a reference is nice.

**Comment by muzikbike** [comment] 2020-07-23 20:56
CPU in F3 debug screen, 7.9GB usable RAM, x64 based processor

**Comment by muzikbike** [comment] 2020-07-26 15:28
With a render distance of 2 and daylight and weather cycle turned off, server performance seems completely fine, with the odd spike when loading new chunks. Much more testing is needed.

**Comment by muzikbike** [comment] 2020-07-26 15:30
okay, seems like "loading a lot of new chunks" is where it seriously struggles.

**Comment by Niko-sk2x** [comment] 2020-08-25 13:15
I know of a few suspect spots, and they are not going to be an easy fix. All of them should get better with bigger cube size. In the end, it's the huge amount of CompletableFutures together with not so efficient implementation of LevelBasedGraph.

You are also on a core i3 CPU, which has 2 cores/4 threads. It's actually slightly slower than my core i5 4200M, despite it's higher frequency. I suspect that the LevelBasedGraph implementation also demands huge CPU cache and/or lower memory latency to be efficient with CC in it's current state. This hits older, otherwise fast, CPUs especially badly.

**Comment by NotStirred** [comment] 2021-06-17 00:41
Closing as this is now outdated, several performance improvements have been made (mainly lighting actually working somewhat)

**Closed as completed by NotStirred** 2021-06-17 00:41 UTC
Labels: Bug, Performance, Cannot reproduce, 1.17
