### ISSUE TITLE
Adding block to world cause incorrect relight.

### ISSUE THREAD

**Issue by Foghrye4** [Barteks2x/CubicChunks#126] opened 2017-01-04 11:03 UTC
![Screenshot](http://i.imgur.com/2mOQoUc.png)

How to repeat:
1. Create flat cubic world.
2. Add a block at level 0.
3. Look around.

Actual version: 8f938ff

In most cases setting block in an angle of cube cause opposite angle of cube under to turn dark.

New tool shows that light levels differs on server and client side:
![Debug tool output](http://i.imgur.com/U4qT9Wf.png)

Adding light emitting blocks cause dark squares to appear in adjusting cubes near light radius end.
![Black squares](http://i.imgur.com/EZi6kP5.png)

**Comment by Niko-sk2x** [comment] 2017-01-04 12:30
This is caused by the cube you are setting block being completely empty before, so the internal storage is null. When you place a block it has to be created and initial light values are zero. This will be fixed when I work on more lighting issues.

**Closed as completed** 2017-01-04 20:25 UTC
Labels: Bug
