### ISSUE TITLE
Game crashes before starting up {Invalid, out of memory}

### ISSUE THREAD

**Issue by the-dragon-42** [Barteks2x/CubicChunks#485] opened 2020-03-26 07:41 UTC
I've currently got these mods running:
- CubicChunks
- CubicWorldGen
- Terra121
- Malisiscore
I've allocated 6GB out of my 8 to forge 1.12.2 2748 but it keeps crashing with Error Code 1 and from what I've googled so far it could be a RAM issue, which I can't fix, but I honestly don't know yet.
I'm really new to this whole GitHub thing so sorry if I'm writing this wrong :P

**Comment by the-dragon-42** [comment] 2020-03-26 07:42
I also haven't been getting a crash report or I'd link it, which _really_ isn't helping :/

**Comment by Niko-sk2x** [comment] 2020-03-26 15:30
First, show the crash log. Without that there is no real way to tell what is wrong for sure. And there always is something. Even if it's not in some file. Also, update forge to latest 1.12.2.

The existence of Error Code (or exit code) suggests JVM issue. I see a few possibilities:
 * You have 32-bit java (unlikely if on mojang launcher or twitch, likely if on other launchers). In that case you need to install 64-bit java (or use mojang or twitch launcher)
 * You actually don't have enough free RAM - which could be caused by a few different things, most likely being that you actually can't let java allocate 6GB **heap** with 8GB of system RAM. Because windows itself is going to be using **at least** 2GB of that, and **heap** is not all that there is in java. Try 3GB and you should be fine.

If the above doesn't help, try also closing some unnecessary programs (do you have chrome with a lot of tabs open? Close some of it).

This is not an issue with the mod and there is nothing I can do to make this any easier, making this more intuitive would have to be done by developers of whatever launcher you are using, so closing this as invalid.

**Closed as completed by Niko-sk2x** 2020-03-26 15:30 UTC
Labels: Invalid

**Comment by the-dragon-42** [comment] 2020-03-27 05:32
[latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/4391681/latest.log)
Here's the latest log running without MalisisCore and 3GB RAM. Sorry there wasn't one in the first report, I didn't know where they were :/

**Comment by Niko-sk2x** [comment] 2020-03-27 13:22
This is a completely different issue and there is not enough information in this log to determine what is wrong. It looks like you have some other mod that is interfering with cubic chunks somehow. Debug.log is needed for more information.
