### ISSUE TITLE
Make ServerHeightMap work with full 32-bit integer range

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#183] opened 2017-05-21 08:10 UTC
I know I created a issue about this already but I finally changed serverheightmap to make it use 32-bit integers. But when compiling it says that there is problem with "test". What can I do to fix this?

**Comment by Niko-sk2x** [comment] 2017-05-21 09:53
This means that you broke ServerHeightMap by doing it. There is a good reason ServerHeightMap only uses 31 bits. It *can* be fixed byt as noone is ever going to use even 31 bits, I doubt doubling the height from 1 billion up and down to 2 billion up and down would make any difference.

**Comment by ModForge** [comment] 2017-05-21 10:53
Just curious about what happens when you reach that point

**Comment by Niko-sk2x** [comment] 2017-05-21 11:42
The game will crash when you rwach max integer. I already did it horizontally once because I was also curious.

**Comment by ModForge** [comment] 2017-05-21 13:13
Ok then

**Comment by ModForge** [comment] 2017-05-21 13:14
Wait what if we use 64 bit integers and put a block on the 33 bit limit?

**Closed as completed by ModForge** 2017-05-21 13:13 UTC
Labels: Enhancement, Low priority

**Comment by Niko-sk2x** [comment] 2017-05-22 01:29
Also, this is duplicate of #139
