### ISSUE TITLE
Buildcraft Quarry & Mining Well Compatibility

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#188] opened 2017-05-24 08:21 UTC
Using CC 0.0.567.0 and Buildcraft 7.99.3.
•Mining Well dug down to Y=0, immediately reset to Y=64 and continued even though there was just air there. Behavior acceptable to me but not expected.
•Quarry dug down to Y=0 and crashed. Can workaround by watching the F3 menu and stopping when it approaches Y=0.

Crash log: https://pastebin.com/FWrE1iMq
Latest.log: https://pastebin.com/tyQ1pP5k

![2017-05-24_00 30 49](https://cloud.githubusercontent.com/assets/8357501/26393595/e5d3229e-402f-11e7-8f36-33b3dee33028.png)
![2017-05-24_03 07 14](https://cloud.githubusercontent.com/assets/8357501/26393594/e5cbdb4c-402f-11e7-9529-f5bd83e0d244.png)

**Comment by Niko-sk2x** [comment] 2017-05-24 09:48
Crash log? And actually, full log (`.minecraft/logs/latest/log`, not launcher output). I wiould like to see wher eit crashes.

**Comment by Niko-sk2x** [comment] 2017-05-24 09:53
Also, if you sart your quarry at some extreme height, just onebug I would expect, but it's fixable:

when it reaches not yet generated chunks it will most likely keep going but won't mine any ores. This is because cubes that are requested to be generated by getBlock/setBlock don't have ores generated (and right now this is by design, I would really like @xcube16 to say something about it)

**Comment by Niko-sk2x** [comment] 2017-05-24 17:36
Also right now quarry just won't work correctly (as also most other BC things) above y=2048. This is because BC uses BlockPos.toLong, and there are only 64 bits to fit x y and z coordinates:

![screenshot](http://i.imgur.com/pbh0ROg.png)

**Comment by Niko-sk2x** [comment] 2017-05-25 06:29
Crash fixed in https://github.com/BuildCraft/BuildCraft/commit/9b9b10f37c5c51f638b8173cc83579b932a0f0a4 and https://github.com/BuildCraft/BuildCraft/commit/0d67d969ca8d171129d557928614551c0dce1066. Just note that this is still alpha version of buildcraft, and cubic chunks isn't even alpha yet. based on my testing, the quarry doesn't even chunkload itself yet (even when cubic chunks does actually support chunkloading to some extent).

Mining well behavior probably looks like that because it resets to y=64 when it reaches "no next position" state. Quarry will now stop at y=0. Some better compatibility may (or may not) happen in the future.

If you want to, submit another issue for quarry and minig well stopping at y=0, this is closed because it no longer crashes.

**Closed as completed by Niko-sk2x** 2017-05-25 06:29 UTC
Labels: Compatibility

**Comment by BaccarWozat** [comment] 2017-05-26 00:57
Stopping at Y=0 is fine, or even your suggestion of "only" going down 256m.
